<a href="https://colab.research.google.com/github/Siarzis/custom-ai/blob/main/multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [1]:
import numpy as np

import random
import copy

import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score

# Generate dataset

In [2]:
# for a single perceptron, the algorithm requires the number of inputs
# to the perceptron as a parameter to be provided

# no_inputs specifices perceptron's number of inputs and is user-defined hyperparameter
inputs = 2

# s value specifies the size of the dataset
s = 1000

training_dataset = np.random.uniform(0, 1, size=(s, inputs+1))

for row in training_dataset:
    if row[1] > row[0]:
        row[2] = 1
    else:
        row[2] = 0

# Plot the dataset

In [ ]:
# Extract horizontal and vertical coordinates from the input values

h_green = []
v_green = []
h_blue = []
v_blue = []

for i, row in enumerate(training_dataset):
    if row[2] == 1:
        h_green.append(training_dataset[i, 0])
        v_green.append(training_dataset[i, 1])
    else:
        h_blue.append(training_dataset[i, 0])
        v_blue.append(training_dataset[i, 1])

# Plot the points
plt.scatter(h_green, v_green, marker='o', s=1, color='green', label='Random Points')
plt.scatter(h_blue, v_blue, marker='o', s=1, color='blue', label='Random Points')
plt.plot([0.0, 1], [0.0, 1], color='black')

# Add labels and title
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Randomly Generated Input Values')

# Display the legend
plt.legend()

# Show the plot
plt.show()

# Initialize model & Forward pass



In [17]:
# configure the learning rate
lr = 0.5

# number of epochs
epochs = 1000

# provide number of neurons in each hidden layer
layer_neurons = [inputs, 2, 2]

weights, hidden, bias, node_delta = [], [], [], []

# the number of rows in w represents the number of neuron in each layer
# the number of columns in w represents the number of inputs of the previous layer
for i in range(1, len(layer_neurons)):

    # initialize the neuron weights
    weights.append(np.zeros((layer_neurons[i], layer_neurons[i-1])))

    hidden.append(np.zeros((layer_neurons[i], 1)))

    node_delta.append(np.zeros((layer_neurons[i], 1)))

# X = sample[:2]
# d = sample[2]

X = np.array([[0.05], [0.1]])
d = np.array([[0.01], [0.99]])

hidden.insert(0, X)

# Set up weights and biases
weights = []
weights.append(np.array([[0.15, 0.2], [0.25, 0.3]]))
weights.append(np.array([[0.4, 0.45], [0.5, 0.55]]))

bias = [0.35, 0.6]

# initialize perceptron

for e in range(epochs):
    # forward pass implementation
    for i in range(1, len(hidden)):
        hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i-1], hidden[i-1])+bias[i-1]))

    print("Epoch: {}".format(e))
    print(hidden[-1])

    weights_old = copy.deepcopy(weights)

    # backward pass implementation

    # iterate layer
    for i in range(1, len(layer_neurons)):
        # compute the error --- square error function is convenient for the gradient computation
        # err = 0.5*((error[-i][j]-hidden[-i][j]) ** 2)

        if i == 1:
            # compute error sensitivity to output
            delta_error_output = -(d-hidden[-i])

            delta_output_net = hidden[-i]*(1-hidden[-i])

            node_delta[-i] = delta_error_output * delta_output_net

            delta_net_weight = np.transpose(hidden[-i-1])

            # compute error sensitivity to weight
            de_dw = delta_error_output * delta_output_net * delta_net_weight
        else:
            delta_error_output = np.dot(weights_old[-i+1], node_delta[-i+1])

            delta_output_net = hidden[-i]*(1-hidden[-i])

            node_delta[-i] = delta_error_output * delta_output_net

            delta_net_weight = np.transpose(hidden[-i-1])

            de_dw = delta_error_output * delta_output_net * delta_net_weight

        weights[-i] = weights[-i] - lr*de_dw

Epoch: 0
[[0.75136507]
 [0.77292847]]
Epoch: 1
[[0.74208787]
 [0.77528466]]
Epoch: 2
[[0.73247621]
 [0.77758097]]
Epoch: 3
[[0.7225377 ]
 [0.77981963]]
Epoch: 4
[[0.71228328]
 [0.78200275]]
Epoch: 5
[[0.70172742]
 [0.78413236]]
Epoch: 6
[[0.69088814]
 [0.7862104 ]]
Epoch: 7
[[0.67978703]
 [0.78823873]]
Epoch: 8
[[0.66844911]
 [0.7902191 ]]
Epoch: 9
[[0.65690263]
 [0.79215322]]
Epoch: 10
[[0.64517866]
 [0.79404269]]
Epoch: 11
[[0.63331071]
 [0.79588906]]
Epoch: 12
[[0.62133416]
 [0.79769381]]
Epoch: 13
[[0.60928567]
 [0.79945835]]
Epoch: 14
[[0.59720251]
 [0.80118402]]
Epoch: 15
[[0.58512194]
 [0.80287211]]
Epoch: 16
[[0.57308049]
 [0.80452387]]
Epoch: 17
[[0.56111342]
 [0.80614048]]
Epoch: 18
[[0.54925412]
 [0.80772306]]
Epoch: 19
[[0.53753365]
 [0.8092727 ]]
Epoch: 20
[[0.5259804 ]
 [0.81079044]]
Epoch: 21
[[0.51461979]
 [0.81227727]]
Epoch: 22
[[0.50347408]
 [0.81373414]]
Epoch: 23
[[0.49256239]
 [0.81516197]]
Epoch: 24
[[0.4819006 ]
 [0.81656164]]
Epoch: 25
[[0.47150152]
 [0.8179339

In [ ]:
# configure the learning rate
lr = 0.5

# number of epochs
epochs = 10

# provide number of neurons in each hidden layer
layer_neurons = [inputs, 2, 2]

weights, hidden, b, node_delta = [], [], [], []

# the number of rows in w represents the number of neuron in each layer
# the number of columns in w represents the number of inputs of the previous layer
for i in range(1, len(layer_neurons)):

    # initialize the neuron weights
    weights.append(np.zeros((layer_neurons[i], layer_neurons[i-1])))

    hidden.append(np.zeros((layer_neurons[i], 1)))

    node_delta.append(np.zeros((layer_neurons[i], 1)))

    # b.append(0)

# X = sample[:2]
# d = sample[2]

X = np.array([[0.05], [0.1]])
d = np.array([[0.01], [0.99]])

# Set up weights and biases
weights = []
weights.append(np.array([[0.15, 0.2], [0.25, 0.3]]))
weights.append(np.array([[0.4, 0.45], [0.5, 0.55]]))

# initialize perceptron

for e in range(epochs):
    # forward pass implementation
    for i in range(len(weights)):
        if i == 0:
            hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i], X)+0.35))
        else:
            hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i], hidden[i-1])+0.6))

    print(hidden)

    hidden.insert(0, X) # THIS IS BUGGY - CHANGE IT

    weights_old = copy.deepcopy(weights)

    # backward pass implementation

    # iterate layer
    for i in range(1, len(layer_neurons)):
        # compute the error --- square error function is convenient for the gradient computation
        # err = 0.5*((error[-i][j]-hidden[-i][j]) ** 2)

        if i == 1:
            # compute error sensitivity to output
            delta_error_output = -(d-hidden[-i])

            delta_output_net = hidden[-i]*(1-hidden[-i])

            node_delta[-i] = delta_error_output * delta_output_net

            delta_net_weight = np.transpose(hidden[-i-1])

            # compute error sensitivity to weight
            de_dw = delta_error_output * delta_output_net * delta_net_weight
        else:
            delta_error_output = np.dot(weights_old[-i+1], node_delta[-i+1])

            delta_output_net = hidden[-i]*(1-hidden[-i])

            node_delta[-i] = delta_error_output * delta_output_net

            delta_net_weight = np.transpose(hidden[-i-1])

            de_dw = delta_error_output * delta_output_net * delta_net_weight

        weights[-i] = weights[-i] - lr*de_dw

#Test forward pass

In [ ]:
# Simple input data
input_data = np.array([[0.1, 0.5]])

# Set up weights and biases
weights = []
weights.append(np.array([[-0.3, 0.1], [0.4, 0.2]]))
weights.append(np.array([[0.1, -0.1]]))

hidden = np.zeros(2)

X = np.array([[0.05], [0.1]])

# Set up weights and biases
w = []
w.append(np.array([[-0.3, 0.1], [0.4, 0.2]]))
w.append(np.array([[0.1, -0.1]]))

# forward pass implementation
for i in range(len(weights)):
    if i == 0:
        for j in range(weights[i].shape[0]):
            hidden[j] = np.sum(weights[i][j] * input_data)
    else:
        print(hidden)
        for j in range(weights[i].shape[0]):
            y = np.sum(weights[i][j] * hidden)

print(y)