<a href="https://colab.research.google.com/github/Siarzis/custom-ai/blob/main/multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [1]:
import numpy as np

import random
import copy

import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score

# Generate dataset

In [2]:
# for a single perceptron, the algorithm requires the number of inputs
# to the perceptron as a parameter to be provided

# no_inputs specifices perceptron's number of inputs and is user-defined hyperparameter
inputs = 2

# s value specifies the size of the dataset
s = 1000

training_dataset = np.random.uniform(0, 1, size=(s, inputs+1))

for row in training_dataset:
    if row[1] > row[0]:
        row[2] = 1
    else:
        row[2] = 0

# Plot the dataset

In [ ]:
# Extract horizontal and vertical coordinates from the input values

h_green = []
v_green = []
h_blue = []
v_blue = []

for i, row in enumerate(training_dataset):
    if row[2] == 1:
        h_green.append(training_dataset[i, 0])
        v_green.append(training_dataset[i, 1])
    else:
        h_blue.append(training_dataset[i, 0])
        v_blue.append(training_dataset[i, 1])

# Plot the points
plt.scatter(h_green, v_green, marker='o', s=1, color='green', label='Random Points')
plt.scatter(h_blue, v_blue, marker='o', s=1, color='blue', label='Random Points')
plt.plot([0.0, 1], [0.0, 1], color='black')

# Add labels and title
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Randomly Generated Input Values')

# Display the legend
plt.legend()

# Show the plot
plt.show()

# Initialize model & Forward pass



In [6]:
# configure the learning rate
lr = 0.5

# number of epochs
epochs = 1

# provide number of neurons in each hidden layer
layer_neurons = [inputs, 2, 2]

weights, hidden, b, error = [], [], [], []

# the number of rows in w represents the number of neuron in each layer
# the number of columns in w represents the number of inputs of the previous layer
for i in range(1, len(layer_neurons)):

    # initialize the neuron weights
    weights.append(np.zeros((layer_neurons[i], layer_neurons[i-1])))

    hidden.append(np.zeros((layer_neurons[i], 1)))

    error.append(np.zeros((layer_neurons[i], 1)))

    # b.append(0)

# initialize perceptron

for e in range(epochs):
    for sample in training_dataset[:1,:]:
        X = sample[:2]
        d = sample[2]

        X = np.array([[0.05], [0.1]])
        d = np.array([[0.01], [0.99]])

        # Set up weights and biases
        weights = []
        weights.append(np.array([[0.15, 0.2], [0.25, 0.3]]))
        weights.append(np.array([[0.4, 0.45], [0.5, 0.55]]))

        # forward pass implementation
        for i in range(len(weights)):
            if i == 0:
                hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i], X)+0.35))
            else:
                hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i], hidden[i-1])+0.6))

        hidden.insert(0, X)

        weights_old = copy.deepcopy(weights)

        # backward pass implementation

        # iterate layer
        for i in range(1, len(layer_neurons)):
            # compute the error --- square error function is convenient for the gradient computation
            # err = 0.5*((error[-i][j]-hidden[-i][j]) ** 2)

            if i == 1:
                # compute error sensitivity to output
                derror_doutput = -(d-hidden[-i])

                doutput_dnet = hidden[-i]*(1-hidden[-i])

                # error[-i] = derror_doutput * doutput_dnet

                dnet_dweight = hidden[-i-1]

                print(derror_doutput)
                print(doutput_dnet)
                print(dnet_dweight)

                # compute error sensitivity to weight
                de_dw = derror_doutput * doutput_dnet * dnet_dweight

                print(de_dw)

                weights[-i] = weights[-i] - lr*de_dw

                print(weights)
            else:
                print('hi')
                # dout_hj_dnet_hj = hidden[-i][j]*(1-hidden[-i][j])

                # dnet_hj_dwk = hidden[-i-1][k]

                # dE_total_dout_hj = 0

                # for l in range(layer_neurons[-i+1]):
                #     print(error[-i+1][j])
                #     dE_total_dout_hj += error[-i+1][j] * weights_old[-i+1][l]

                # print(dE_total_dout_hj, dout_hj_dnet_hj, dnet_hj_dwk)

                # de_dw = dE_total_dout_hj * dout_hj_dnet_hj * dnet_hj_dwk



[[ 0.74136507]
 [-0.21707153]]
[[0.1868156 ]
 [0.17551005]]
[[0.59326999]
 [0.59688438]]
[[ 0.08216704]
 [-0.02274024]]
[array([[0.15, 0.2 ],
       [0.25, 0.3 ]]), array([[0.35891648, 0.40891648],
       [0.51137012, 0.56137012]])]
hi


In [ ]:
# configure the learning rate
lr = 0.5

# number of epochs
epochs = 1

# provide number of neurons in each hidden layer
layer_neurons = [inputs, 2, 2]

weights, hidden, b, error = [], [], [], []

# the number of rows in w represents the number of neuron in each layer
# the number of columns in w represents the number of inputs of the previous layer
for i in range(1, len(layer_neurons)):

    # initialize the neuron weights
    weights.append(np.zeros((layer_neurons[i], layer_neurons[i-1])))

    hidden.append(np.zeros((layer_neurons[i], 1)))

    error.append(np.zeros((layer_neurons[i], 1)))

    # b.append(0)

# initialize perceptron

for e in range(epochs):
    for sample in training_dataset[:1,:]:
        X = sample[:2]
        d = sample[2]

        X = np.array([[0.05], [0.1]])
        d = np.array([[0.01], [0.99]])

        # Set up weights and biases
        weights = []
        weights.append(np.array([[0.15, 0.2], [0.25, 0.3]]))
        weights.append(np.array([[0.4, 0.45], [0.5, 0.55]]))

        # forward pass implementation
        for i in range(len(weights)):
            if i == 0:
                hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i], X)+0.35))
            else:
                hidden[i] = 1/(1 + 1/np.exp(np.dot(weights[i], hidden[i-1])+0.6))

        hidden.insert(0, X)

        weights_old = copy.deepcopy(weights)

        # backward pass implementation

        # iterate layer
        for i in range(1, len(layer_neurons)):
            # iterate neurons per layer
            for j in range(layer_neurons[-i]):
            # iterate weights per neuron
                for k in range(layer_neurons[-i-1]):
                    # compute the error --- square error function is convenient for the gradient computation
                    # err = 0.5*((error[-i][j]-hidden[-i][j]) ** 2)

                    if i == 1:
                        # compute error sensitivity to output
                        print(i,j,k)
                        de_do = -(d[j][0]-hidden[-i][j])

                        do_dh = hidden[-i][j]*(1-hidden[-i][j])

                        error[-i][j] = de_do * do_dh

                        dh_dw = hidden[-i-1][k]

                        # compute error sensitivity to weight
                        de_dw = de_do * do_dh * dh_dw
                    else:
                        dout_hj_dnet_hj = hidden[-i][j]*(1-hidden[-i][j])

                        dnet_hj_dwk = hidden[-i-1][k]

                        dE_total_dout_hj = 0

                        for l in range(layer_neurons[-i+1]):
                            print(error[-i+1][j])
                            dE_total_dout_hj += error[-i+1][j] * weights_old[-i+1][l]

                        print(dE_total_dout_hj, dout_hj_dnet_hj, dnet_hj_dwk)

                        de_dw = dE_total_dout_hj * dout_hj_dnet_hj * dnet_hj_dwk

                        print(weights)


                    weights[-i][j][k] = weights[-i][j][k] - lr*de_dw[0]


#Test forward pass

In [ ]:
# Simple input data
input_data = np.array([[0.1, 0.5]])

# Set up weights and biases
weights = []
weights.append(np.array([[-0.3, 0.1], [0.4, 0.2]]))
weights.append(np.array([[0.1, -0.1]]))

hidden = np.zeros(2)

X = np.array([[0.05], [0.1]])

# Set up weights and biases
w = []
w.append(np.array([[-0.3, 0.1], [0.4, 0.2]]))
w.append(np.array([[0.1, -0.1]]))

# forward pass implementation
for i in range(len(weights)):
    if i == 0:
        for j in range(weights[i].shape[0]):
            hidden[j] = np.sum(weights[i][j] * input_data)
    else:
        print(hidden)
        for j in range(weights[i].shape[0]):
            y = np.sum(weights[i][j] * hidden)

print(y)